### ISSUE TITLE
Update the documentation website with the latest changes

### ISSUE THREAD

**Issue by nii236** [adewes/blitzdb#53]
I spent ages trying to fix the meta class primary key variable (pk instead of primary_key) because the documentation on the website was incorrect. I began preparing a pull request only to find that the documentation in the git repo itself was already fixed on the 15th of March!

Please update the readthedocs.org website for Blitzdb for future users.

**Comment by adewes** [comment]
Thanks for pointing this out @nii236 , there was a problem with the post-commit hook on RTD which I fixed, so the documentation should be built automatically again.
